### ISSUE TITLE
Sign in with Facebook is clipped for large size button.

### ISSUE THREAD

**Issue by jokerham** [emreesen27/Flutter-Sign-in-Button#20] opened 2022-12-13 14:32 UTC
I have not checked for all buttonTypes, but for large size Facebook button, the widths should be larger than 256.

**Comment by emreesen27** [comment] 2022-12-13 17:06
The width value is customizable. If you are having an overflow problem, you can use it like this.

```dart
  buttonType: ButtonType.facebook,
  buttonSize: ButtonSize.large,
  width: 260,
```

**Comment by jokerham** [comment] 2022-12-14 11:44
Yes I know, but since Facebook buttonType is used so frequently, it should be defaulted to 256 instead of 250.

**Comment by emreesen27** [comment] 2024-04-18 17:46
Since this is not a bug, I am closing it.

**Closed by emreesen27** 2024-04-18 17:46 UTC
